### ISSUE TITLE
Crash when almost infinity barrel is connected to ME fluid storage bus

### ISSUE THREAD

**Issue by eliphatfs** [CJ-MC-Mods/IBHSTD#118]
#### Overloaded Version: 0.0.98
As written in title. This always happens when ticking. (Logged in several times and it all crashed the server.)
I am playing FTB university 1.16.

```plain
[25Mar2023 19:28:31.044] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Ticking GridNode
	Index: 23
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		2: NORMAL
		3: ASM: class com.dynamic_view.event.EventHandler onDedicatedServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2775/1684851897@17d4a2e7
		5: ASM: class dev.ftb.mods.ftbessentials.FTBEEventHandler serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		6: ASM: class com.wuest.prefab.structures.events.StructureEventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		7: ASM: class com.feed_the_beast.mods.ftbbackups.FTBBackups serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		8: ASM: class com.mrcrayfish.guns.common.DelayedTask onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		9: ASM: class shadows.placebo.util.PlaceboTaskQueue tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		10: ASM: class noobanidus.mods.lootr.entity.EntityTicker onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		11: ASM: com.github.alexthe666.citadel.server.CitadelEvents@21014036 onServerTickEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		12: ASM: class noobanidus.mods.lootr.block.tile.TileTicker serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		13: ASM: class yesman.epicfight.events.EntityEvents tickServerEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		14: ASM: net.minecraftforge.common.ForgeInternalHandler@5f25e595 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		15: net.minecraftforge.eventbus.EventBus$$Lambda$2775/1684851897@6152cd0d
		16: ASM: class cofh.core.event.CoreCommonEvents serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		17: ASM: class owmii.lib.util.Server tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		18: ASM: me.desht.pneumaticcraft.common.amadron.EventHandlerAmadron@671d235e amadronHousekeeping(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		19: ASM: class me.desht.pneumaticcraft.common.tileentity.TileEntityPressureChamberWall$PressureWallStateManager onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		20: ASM: class com.hollingsworth.arsnouveau.api.event.EventQueue serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		21: ASM: me.ichun.mods.ichunutil.common.core.EventHandlerServer@3ed5d28a onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		22: ASM: stepsword.mahoutsukai.handlers.ServerHandler@a954e2 serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		23: net.minecraftforge.eventbus.EventBus$$Lambda$2775/1684851897@195071e8
		24: ASM: class com.simibubi.create.events.CommonEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		25: ASM: com.mrcrayfish.obfuscate.common.data.SyncedPlayerData@67908b1e onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		26: ASM: mekanism.common.CommonWorldTickHandler@71ca8e2d onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		27: ASM: Network Registry:
{} onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		28: ASM: codechicken.enderstorage.network.TankSynchroniser@3d1bef9b tickEnd(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		29: ASM: org.cyclops.integrateddynamics.core.TickHandler@2d011a7d onTick(Lnet/minecraftforge/event/TickEvent;)V
		30: ASM: org.cyclops.integrateddynamics.core.NoteBlockEventReceiver@25f17799 onTick(Lnet/minecraftforge/event/TickEvent;)V
		31: LOWEST
		32: ASM: class cofh.core.event.AreaEffectEvents handleTickEndEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
net.minecraft.crash.ReportedException: Ticking GridNode
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:117)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:38)
	at appeng.me.Grid.update(Grid.java:249)
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:314)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:106)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at appeng.fluids.util.AEFluidStack.fromFluidStack(AEFluidStack.java:80)
	at appeng.fluids.parts.FluidHandlerAdapter$InventoryCache.handleFluidChanged(FluidHandlerAdapter.java:239)
	at appeng.fluids.parts.FluidHandlerAdapter$InventoryCache.handlePossibleSlotChanges(FluidHandlerAdapter.java:215)
	at appeng.fluids.parts.FluidHandlerAdapter$InventoryCache.update(FluidHandlerAdapter.java:185)
	at appeng.fluids.parts.FluidHandlerAdapter.onTick(FluidHandlerAdapter.java:115)
	at appeng.fluids.parts.FluidStorageBusPart.tickingRequest(FluidStorageBusPart.java:161)
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:84)
	... 12 more

[25Mar2023 19:28:31.047] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking GridNode
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:117) ~[appliedenergistics2:8.4.7]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:38) ~[appliedenergistics2:8.4.7]
	at appeng.me.Grid.update(Grid.java:249) ~[appliedenergistics2:8.4.7]
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:314) ~[appliedenergistics2:8.4.7]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:106) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
	at appeng.fluids.util.AEFluidStack.fromFluidStack(AEFluidStack.java:80) ~[appliedenergistics2:8.4.7]
	at appeng.fluids.parts.FluidHandlerAdapter$InventoryCache.handleFluidChanged(FluidHandlerAdapter.java:239) ~[appliedenergistics2:8.4.7]
	at appeng.fluids.parts.FluidHandlerAdapter$InventoryCache.handlePossibleSlotChanges(FluidHandlerAdapter.java:215) ~[appliedenergistics2:8.4.7]
	at appeng.fluids.parts.FluidHandlerAdapter$InventoryCache.update(FluidHandlerAdapter.java:185) ~[appliedenergistics2:8.4.7]
	at appeng.fluids.parts.FluidHandlerAdapter.onTick(FluidHandlerAdapter.java:115) ~[appliedenergistics2:8.4.7]
	at appeng.fluids.parts.FluidStorageBusPart.tickingRequest(FluidStorageBusPart.java:161) ~[appliedenergistics2:8.4.7]
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:84) ~[appliedenergistics2:8.4.7]
	... 12 more
```

**Comment by cjm721** [comment]
Please attach the crash report file. Nothing in the message reports anything from overloaded

**Comment by eliphatfs** [comment]
[crash-2023-03-25_20.05.33-server.txt](https://github.com/CJ-MC-Mods/Overloaded/files/11071266/crash-2023-03-25_20.05.33-server.txt)
Nothing in the crash report seems to be reporting anything from overloaded, but it is likely an integration issue, and I am reporting on both sides.
