### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by louisisalilbitch** [CJ-MC-Mods/IBHSTD#76]
#### Overloaded Version: 0.0.66
Time: 15/07/19 11:58 AM
Description: Rendering overlay

java.lang.NoSuchMethodError: net.minecraftforge.client.event.TextureStitchEvent$Pre.addSprite(Lnet/minecraft/util/ResourceLocation;)Z
	at com.cjm721.overloaded.client.render.dynamic.general.ResizeableTextureGenerator.texturePre(ResizeableTextureGenerator.java:38) ~[?:0.0.66] {pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_65_ResizeableTextureGenerator_texturePre_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:163) ~[?:27.0] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$25(ModLoader.java:217) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:190) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:217) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:183) ~[?:?] {}
	at net.minecraft.client.renderer.texture.AtlasTexture.func_215254_a(AtlasTexture.java:87) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.texture.SpriteUploader.func_212854_a_(SourceFile:29) ~[?:?] {}
	at net.minecraft.client.renderer.texture.SpriteUploader.func_212854_a_(SourceFile:11) ~[?:?] {}
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_74] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.cjm721.overloaded.client.render.dynamic.general.ResizeableTextureGenerator.texturePre(ResizeableTextureGenerator.java:38)
	at net.minecraftforge.eventbus.ASMEventHandler_65_ResizeableTextureGenerator_texturePre_Pre.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:163)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$25(ModLoader.java:217)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:885)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:77)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:62)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Mac OS X (x86_64) version 10.14.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1226069464 bytes (1169 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Launched Version: 1.14.3-forge-27.0.13
	LWJGL: 3.2.2 build 10
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-12.9.22, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by cjm721** [comment]
Update forge. This error happened because you are not beyond version 23
