### ISSUE TITLE
Constant error in client console

### ISSUE THREAD

**Issue by CritLoren** [CJ-MC-Mods/IBHSTD#96]
#### Overloaded Version: 0.0.86
```Something has changed private internal state in an invalid way. Resetting State.
java.lang.IllegalStateException: private internal state changed. Stack's Tag Compound is null
	at com.cjm721.overloaded.storage.itemwrapper.IntEnergyWrapper.getStorage(IntEnergyWrapper.java:96)
	at com.cjm721.overloaded.storage.itemwrapper.IntEnergyWrapper.getEnergyStored(IntEnergyWrapper.java:75)
	at com.cjm721.overloaded.item.functional.PowerModItem.lambda$getDurabilityForDisplay$1(PowerModItem.java:65)
	at com.cjm721.overloaded.item.functional.PowerModItem$$Lambda$10636/2075952031.apply(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.lambda$map$0(LazyOptional.java:184)
	at net.minecraftforge.common.util.LazyOptional$$Lambda$8943/1710023146.get(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:116)
	at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:219)
	at com.cjm721.overloaded.item.functional.PowerModItem.getDurabilityForDisplay(PowerModItem.java:66)
	at com.cjm721.overloaded.item.functional.ItemMultiTool.getDurabilityForDisplay(ItemMultiTool.java:66)
	at net.minecraft.client.renderer.ItemRenderer.func_180453_a(ItemRenderer.java:257)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_146977_a(ContainerScreen.java:221)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:91)
	at moze_intel.projecte.gameObjs.gui.PEContainerScreen.render(PEContainerScreen.java:17)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:359)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$459/298287232.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)```

**Comment by cjm721** [comment]
Would report this to ProjectE. Something is clearing the Stack's NBT data between construction and usage.

In construction I set the [tag](https://github.com/CJ-MC-Mods/Overloaded/blob/1.15/src/main/java/com/cjm721/overloaded/storage/itemwrapper/IntEnergyWrapper.java#L27) to be a valid value. So only way for it not to be valid later is something is clearing the NBT data.
