### ISSUE TITLE
Multi-tool not destroying blocks

### ISSUE THREAD

**Issue by NumbaTw0** [CJ-MC-Mods/IBHSTD#97]
#### Overloaded Version: <1.15.2-0.0.86>
As the title says, the newest forge version prevents the multi-tool from breaking blocks.  I confirmed the issue by creating a profile with only forge and Overloaded.  The blocks disappear but are not broken.

**Comment by cjm721** [comment]
Forge changed something as it still works on recommended (31.1.0)

**Comment by cjm721** [comment]
Yep 1.15.2-31.1.79 broke it.

```[m[1;31m[13:56:22] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:218) ~[?:?] {re:classloading}
	at com.cjm721.overloaded.util.PlayerInteractionUtil.removeBlock(PlayerInteractionUtil.java:88) ~[?:0.0.86] {re:classloading}
	at com.cjm721.overloaded.util.PlayerInteractionUtil.tryHarvestBlock(PlayerInteractionUtil.java:67) ~[?:0.0.86] {re:classloading}
	at com.cjm721.overloaded.item.functional.ItemMultiTool.breakAndUseEnergy(ItemMultiTool.java:137) ~[?:0.0.86] {re:classloading}
	at com.cjm721.overloaded.item.functional.ItemMultiTool.leftClickOnBlockServer(ItemMultiTool.java:192) ~[?:0.0.86] {re:classloading}
	at com.cjm721.overloaded.network.handler.PlayerMessageHandler.lambda$accept$0(PlayerMessageHandler.java:26) ~[?:0.0.86] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
	at com.cjm721.overloaded.network.handler.PlayerMessageHandler.accept(PlayerMessageHandler.java:26) ~[?:0.0.86] {re:classloading}
	at com.cjm721.overloaded.network.handler.PlayerMessageHandler.accept(PlayerMessageHandler.java:10) ~[?:0.0.86] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_121] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_121] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] {}```
